fel: use winnanosleep instead of nanosleep
fix 'undefined reference to nanosleep'.
winnanosleep took from here "https://gist.github.com/Youka/4153f12cf2e17a77314c"